### PR TITLE
Add Author to default column list

### PR DESCRIPTION
**Pull request by ivan-c**

### CODE REVIEW

**Review by achen2401 — APPROVED** [review]

**Review by pbugni — COMMENTED** [review]
as this is multi line, i think it'd be more legible to add a line break per column

**Review by mcjustin — APPROVED** [review]
I don't know why `$$` here is manifested as a single `$` on the system, but that doesn't matter much - the pattern has been working!

**Comment by ivan-c** [comment]
> as this is multi line, i think it'd be more legible to add a line break per column

Done (see 062ac1e)! Had to consult [yaml-multiline](https://yaml-multiline.info/), but looks to be working on dev

**Comment by ivan-c** [comment]
> I don't know why `$$` here is manifested as a single `$` on the system, but that doesn't matter much - the pattern has been working!

The `$$` is used only for docker-compose, to escape a normal `$`, which can be used for interpolating environment variables into the docker-compose yaml, eg `${POSTGRES_IMAGE_TAG}`


>You can use a $$ (double-dollar sign) when your configuration needs a literal dollar sign. This also prevents Compose from interpolating a value, so a $$ allows you to refer to environment variables that you don’t want processed by Compose.


https://docs.docker.com/compose/compose-file/12-interpolation/

**Pull request merged**
