### PR TITLE
Allow all FHIR REST verbs through CORS

### PR DESCRIPTION
**Pull request by ivan-c**
Allow all [FHIR REST](https://www.hl7.org/fhir/http.html) verbs through CORS

### CODE REVIEW

**Review by pbugni — APPROVED** [review]
Ah, a `traefik` solution.  Much better, thank you.

**Review by hannahburkhardt — APPROVED** [review]

**Review by jhowe-uw — COMMENTED** [review]
Looks good.

https://github.com/traefik/traefik/issues/8796 refers to an older traefik release.

I would like to see accessControlAllowOriginList be more restrictive. Perhaps wire in the top level TLD?

**Comment by pbugni** [comment]
@ivan-c we should consider pushing similar changes to the other `*-environment` repos.  Let me know if you want to divide the work, there.

**Comment by ivan-c** [comment]
> I would like to see accessControlAllowOriginList be more restrictive. Perhaps wire in the top level TLD?

@jhowe-uw 

I tried using `$BASE_DOMAIN` with both `accessControlAllowOriginList` and `accessControlAllowOriginListRegex` but couldn't get it to work easily, without introducing another env var to manage.

I've created a [PT story to track this](https://www.pivotaltracker.com/story/show/183384480), but I'm planning to test out `accessControlAllowOriginListRegex` a bit more

**Pull request merged**
